<?php

namespace TarasTestBundle\Repository;

/**
 * Agreement_regRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Agreement_regRepository extends \Doctrine\ORM\EntityRepository
{
}
