<?php

namespace TarasTestBundle\Repository;

/**
 * CitationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitationsRepository extends \Doctrine\ORM\EntityRepository
{
}
