<?php

namespace TarasTestBundle\Repository;

/**
 * DeptStructRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeptStructRepository extends \Doctrine\ORM\EntityRepository
{
}
