<?php

namespace TarasTestBundle\Repository;

/**
 * EnterprisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesRepository extends \Doctrine\ORM\EntityRepository
{
}
