<?php

namespace TarasTestBundle\Repository;

/**
 * HoldingStructRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoldingStructRepository extends \Doctrine\ORM\EntityRepository
{
}
