<?php

namespace TarasTestBundle\Repository;

/**
 * MetaStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaStructureRepository extends \Doctrine\ORM\EntityRepository
{
}
